// Generated by CoffeeScript 1.7.1
(function() {
  var Package;

  Package = require('./package');

  exports.build = function(options) {
    var pkg;
    pkg = new Package(options);
    return pkg.build();
  };

}).call(this);
